### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by eleluong** [VinAIResearch/PhoGPT#1]
As far as i know from reading your paper, you guys used data created by chatgpt, but still you guys release as commercial model. The terms of use of OpenAI show that you can not use use output from the Services to develop models that compete with OpenAI, so please check out license.
https://openai.com/policies/terms-of-use

**Comment by datquocnguyen** [comment]
I do not get it. Where did you get such "commercial model" information?
Our license is similar to LLama-2.

**Comment by eleluong** [comment]
Yeah, but Llama2 did not directly use data created by chatgpt (or used but not confirm ) like you guys so license problem is different, and i think your model maybe for research or non commercial purpose only.

**Comment by datquocnguyen** [comment]
I don't get your point. We do not use the open-source PhoGPT for commercial applications or to compete with OpenAI. Others may use PhoGPT for research or commercial purposes, being responsible for their own applications.
