### ISSUE TITLE
[Question] Hardware requirements with vLLM

### ISSUE THREAD

**Issue by hodacthanhminh** [VinAIResearch/PhoGPT#13]
> To fully fine-tune vinai/PhoGPT-7B5 or vinai/PhoGPT-7B5-Instruct on a single GPU A100 with 40GB memory, it is advisable to employ the decoupled_lionw optimizer with a device_train_microbatch_size set to 1.

How about minimum and recommended hardware requirements when fine-tune vinai/PhoGPT-7B5 with vLLM?

**Comment by datquocnguyen** [comment]
vLLM is an inference framework only.
