### ISSUE TITLE
Mình sử dụng model này bằng CPU được không bạn ơi?

### ISSUE THREAD

**Issue by dinhan92** [VinAIResearch/PhoGPT#16]
Mình thấy hướng dẫn là dùng CUDA, mình chạy model này bằng CPU được không bạn? Cấu hình phải như thế nào mới chạy ngon ạ?

**Comment by vinhmdev** [comment]
Tôi cũng vậy, không dùng cpu được

**Comment by phatjkk** [comment]
Hầu hết các mô hình ngôn ngữ cần chạy trên GPU bạn nha, CPU sẽ không chạy nổi đâu.

**Comment by datquocnguyen** [comment]
Yes, you might want to use https://github.com/ggerganov/llama.cpp that supports "MPT"-type model, including PhoGPT.
