### ISSUE TITLE
Redistributing the model in other format

### ISSUE THREAD

**Issue by nviet** [VinAIResearch/PhoGPT#18]
Hello,

I was able to use phoGPT in CPU-only mode with [_llama.cpp_](https://github.com/ggerganov/llama.cpp) . I would want to convert the model into the _llama.cpp_'s own format (.GGUF) and post it to HuggingFace (similar to [this repo](https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF) for example). I have gone through the LICENSE file and it looks like this would be fine. However I still want to make sure if am I allowed to perform such action?

Regards,

**Comment by datquocnguyen** [comment]
Yes.
Details are presented in the Section "1. License Rights and Redistribution." in the LICENSE.
