### ISSUE TITLE
Error message: "llama.cpp error: 'done_getting_tensors: wrong number of tensors; expected 388, got 195'"

### ISSUE THREAD

**Issue by jackNhat** [VinAIResearch/PhoGPT#23]
I  converted the model into the llama.cpp's own format (.GGUF). And this model could run successful in colab like snapshot. 

![PhoGPT-error](https://github.com/VinAIResearch/PhoGPT/assets/9624815/88a63f32-4864-4351-91e8-88bd88a4b2e4)

But when i loaded this model in LLM Studio or Jan, i got error message. Anyone met this problem? How to resolve this?

![LLMStudio-error](https://github.com/VinAIResearch/PhoGPT/assets/9624815/308740f6-ba28-4cf6-930b-0c25c244a403)

Many thanks!

**Comment by xtfocus** [comment]
Likely a duplicated of my opening issue #22

**Comment by datquocnguyen** [comment]
See: https://github.com/ggerganov/llama.cpp/pull/5638

**Comment by churongcon** [comment]
![image](https://github.com/VinAIResearch/PhoGPT/assets/26823364/d314a7de-32a9-4025-a31e-61ca74748e8c)
@datquocnguyen Not working

**Comment by 001123** [comment]
<img width="1310" alt="image" src="https://github.com/VinAIResearch/PhoGPT/assets/32441266/d375fdf4-e283-401d-a605-3083773f406b">

Same issue

**Comment by datquocnguyen** [comment]
@001123 @churongcon Please could you try installing/compiling llama.cpp from this specific commit and then redo the conversion step (to create the .gguf file): 

https://github.com/jordankanter/llama.cpp/tree/87a41f53ae3a01dde4c198df72cfb99ba2c9f586

```
git clone https://github.com/jordankanter/llama.cpp
git checkout 87a41f53ae3a01dde4c198df72cfb99ba2c9f586
```

**Comment by datquocnguyen** [comment]
@001123 @churongcon, please disregard my previous comment. I have found the reason. "llama.cpp" has been modified, resulting in a converted version of phogpt-4b being associated with 387 tensors, instead of the previous 388. To load it with the latest version of Studio, you can simply reconvert phogpt-4b using the latest "llama.cpp".

**Comment by datquocnguyen** [comment]
@001123 @churongcon please try https://huggingface.co/vinai/PhoGPT-4B-Chat-gguf
