### ISSUE TITLE
hardware requirements to run finetune

### ISSUE THREAD

**Issue by trung-nw** [VinAIResearch/PhoGPT#26]
I ran the sample finetune with default settings on Nvidia A100 40Gb but got OOM. can we get finetune successfully on Nvidia A100 40Gb hardware? any updates for the settings to get it. thank you.

**Comment by datquocnguyen** [comment]
Yes, A100 40GB is more than enough to do full-weight fine-tuning of the 4B model.
That's what I have been using.
