### ISSUE TITLE
Temporarily set the `instruct` version private 

### ISSUE THREAD

**Issue by datquocnguyen** [VinAIResearch/PhoGPT#4]
We temporarily set the `instruct` version private to reinvestigate its safety level. 
We will make it public within this week.

**Comment by datquocnguyen** [comment]
Available, works with all transformers version.

**Comment by hacbachvotu** [comment]
![z4876691733259_7426ad5b582f9fc096dcd0181a9a32fa](https://github.com/VinAIResearch/PhoGPT/assets/124884827/66c9ff0a-da7a-4b85-8d21-5266df9eb9dc)
Why do I get this error, author?

**Comment by datquocnguyen** [comment]
code?

**Comment by hacbachvotu** [comment]
> code?

![z4876767591002_1b2f96f80a718b30c9094f1c0ba59dd0](https://github.com/VinAIResearch/PhoGPT/assets/124884827/d62a849e-8263-490b-9fab-9164851dd0f4)
![z4876766864816_c738b76f6dc21941b2efede54fc17c12](https://github.com/VinAIResearch/PhoGPT/assets/124884827/864811b3-44bb-41ed-ac41-b6d021faf221)
Here it is, thanks for your support!

**Comment by datquocnguyen** [comment]
does the following code work in your side? 

```
from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer  
  
model_path = "vinai/PhoGPT-7B5-Instruct"  
  
config = AutoConfig.from_pretrained(model_path, trust_remote_code=True)  
config.init_device = "cuda"
# config.attn_config['attn_impl'] = 'triton' # Enable if "triton" installed!
  
model = AutoModelForCausalLM.from_pretrained(  
    model_path, config=config, torch_dtype=torch.bfloat16, trust_remote_code=True  
)
# If your GPU does not support bfloat16:
# model = AutoModelForCausalLM.from_pretrained(model_path, config=config, torch_dtype=torch.float16, trust_remote_code=True)
model.eval()  
  
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)  
  
PROMPT = "### Câu hỏi:\n{instruction}\n\n### Trả lời:"  
  
input_prompt = PROMPT.format_map(  
    {"instruction": "xin chào"}  
)  
  
input_ids = tokenizer(input_prompt, return_tensors="pt")  
  
outputs = model.generate(  
    inputs=input_ids["input_ids"].to("cuda"),  
    attention_mask=input_ids["attention_mask"].to("cuda"),  
    do_sample=True,  
    temperature=1.0,  
    top_k=50,  
    top_p=0.9,  
    max_new_tokens=1024,  
    eos_token_id=tokenizer.eos_token_id,  
    pad_token_id=tokenizer.pad_token_id  
)  
  
response = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]  
response = response.split("### Trả lời:")[1]
```

**Comment by hacbachvotu** [comment]
> does the following code work in your side?
> 
> ```
> from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer  
>   
> model_path = "vinai/PhoGPT-7B5-Instruct"  
>   
> config = AutoConfig.from_pretrained(model_path, trust_remote_code=True)  
> config.init_device = "cuda"
> # config.attn_config['attn_impl'] = 'triton' # Enable if "triton" installed!
>   
> model = AutoModelForCausalLM.from_pretrained(  
>     model_path, config=config, torch_dtype=torch.bfloat16, trust_remote_code=True  
> )
> # If your GPU does not support bfloat16:
> # model = AutoModelForCausalLM.from_pretrained(model_path, config=config, torch_dtype=torch.float16, trust_remote_code=True)
> model.eval()  
>   
> tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)  
>   
> PROMPT = "### Câu hỏi:\n{instruction}\n\n### Trả lời:"  
>   
> input_prompt = PROMPT.format_map(  
>     {"instruction": "xin chào"}  
> )  
>   
> input_ids = tokenizer(input_prompt, return_tensors="pt")  
>   
> outputs = model.generate(  
>     inputs=input_ids["input_ids"].to("cuda"),  
>     attention_mask=input_ids["attention_mask"].to("cuda"),  
>     do_sample=True,  
>     temperature=1.0,  
>     top_k=50,  
>     top_p=0.9,  
>     max_new_tokens=1024,  
>     eos_token_id=tokenizer.eos_token_id,  
>     pad_token_id=tokenizer.pad_token_id  
> )  
>   
> response = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]  
> response = response.split("### Trả lời:")[1]
> ```

How can i test this code? Sorry, I'm a bit bad at this.

**Comment by hacbachvotu** [comment]
> does the following code work in your side?
> 
> ```
> from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer  
>   
> model_path = "vinai/PhoGPT-7B5-Instruct"  
>   
> config = AutoConfig.from_pretrained(model_path, trust_remote_code=True)  
> config.init_device = "cuda"
> # config.attn_config['attn_impl'] = 'triton' # Enable if "triton" installed!
>   
> model = AutoModelForCausalLM.from_pretrained(  
>     model_path, config=config, torch_dtype=torch.bfloat16, trust_remote_code=True  
> )
> # If your GPU does not support bfloat16:
> # model = AutoModelForCausalLM.from_pretrained(model_path, config=config, torch_dtype=torch.float16, trust_remote_code=True)
> model.eval()  
>   
> tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)  
>   
> PROMPT = "### Câu hỏi:\n{instruction}\n\n### Trả lời:"  
>   
> input_prompt = PROMPT.format_map(  
>     {"instruction": "xin chào"}  
> )  
>   
> input_ids = tokenizer(input_prompt, return_tensors="pt")  
>   
> outputs = model.generate(  
>     inputs=input_ids["input_ids"].to("cuda"),  
>     attention_mask=input_ids["attention_mask"].to("cuda"),  
>     do_sample=True,  
>     temperature=1.0,  
>     top_k=50,  
>     top_p=0.9,  
>     max_new_tokens=1024,  
>     eos_token_id=tokenizer.eos_token_id,  
>     pad_token_id=tokenizer.pad_token_id  
> )  
>   
> response = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]  
> response = response.split("### Trả lời:")[1]
> ```

![z4876925505928_f2a178476b7f80bf7ffee85420ffefc9](https://github.com/VinAIResearch/PhoGPT/assets/124884827/3b8c54ba-864c-4068-9468-864141501193)
I created a python file and used the code you sent, edited the path to the model in the internal drive and got this error:
