### ISSUE TITLE
Which prompt format we use  for PhoGPT without instruct model!

### ISSUE THREAD

**Issue by lamkhatinh** [VinAIResearch/PhoGPT#6]
I run this code without instruct model, but the code may be adapt with instruct only.
Could you provide PROMPT format for model without instruct?

**Comment by datquocnguyen** [comment]
The base pre-trained model does not follow instructions: PROMPT = "{input_text}".
You would have to fine-tune the base model to follow instructions.

**Comment by ductuan-nguyen** [comment]
Btw, could you provide the prompt format for context-based question answering?

**Comment by datquocnguyen** [comment]
@ductuan-nguyen 
PROMPT = "### Câu hỏi:\nDựa vào văn bản sau đây:\n{Insert context here}\nHãy trả lời câu hỏi: {Insert question here}\n\n### Trả lời:"
