### ISSUE TITLE
PhoGPT-7B5-Instruct has only one word repeated over and over again.

### ISSUE THREAD

**Issue by hacbachvotu** [VinAIResearch/PhoGPT#7]
![z4876691733259_7426ad5b582f9fc096dcd0181a9a32fa](https://github.com/VinAIResearch/PhoGPT/assets/124884827/7505ba8e-62c6-4b7c-b0af-1fb35ff936c0)

PhoGPT-7B5-Instruct has only one word repeated over and over again when i generate! Why does this error appear, everyone? I only have this problem with this model.

**Comment by datquocnguyen** [comment]
Closed!
Following the same question from you in this thread: https://github.com/VinAIResearch/PhoGPT/issues/4 
You might want to install torch, transformers, and/or run the example code (on Google Colab) with GPU.

**Comment by hacbachvotu** [comment]
> Closed! Following the same question from you in this thread: #4 You might want to install torch, transformers, and/or run the example code (on Google Colab) with GPU.

I have installed all with the latest version and all other models run smoothly except this one.

**Comment by datquocnguyen** [comment]
https://github.com/VinAIResearch/PhoGPT/issues/4#issuecomment-1807924908 
CUDA_VISIBLE_DEVICES=0 python testscript.py 
would generate "Xin chào. Tôi có thể giúp gì cho bạn?".

**Comment by hacbachvotu** [comment]
> [#4 (comment)](https://github.com/VinAIResearch/PhoGPT/issues/4#issuecomment-1807924908) CUDA_VISIBLE_DEVICES=0 python testscript.py would generate "Xin chào. Tôi có thể giúp gì cho bạn?".

sorry i don't know what did you say! i use oobabooga.

**Comment by hacbachvotu** [comment]
![z4876946639218_adda9a67200c95d05dac20fe8aecb598](https://github.com/VinAIResearch/PhoGPT/assets/124884827/33c3643e-6d8e-4658-a730-c3a0ad8b5214)

![z4876925505928_f2a178476b7f80bf7ffee85420ffefc9](https://github.com/VinAIResearch/PhoGPT/assets/124884827/d0e7199e-9f9f-4964-abec-5642e59faed0)
everythings ok when i use another model.

**Comment by hacbachvotu** [comment]
![z4879313057704_24d48ae641cad8d14ece01ec28238d9c](https://github.com/VinAIResearch/PhoGPT/assets/124884827/70c94bbb-e3b4-4945-961b-d0d6a2372a8e)
![z4879313559849_2d771ddddec3f1ac5cece45da7d08089](https://github.com/VinAIResearch/PhoGPT/assets/124884827/533a9017-c85a-4eb6-ab13-886b6e43f4e9)
 everything ok when i use another model. I don't understand why only this model of yours is having problems.

**Comment by datquocnguyen** [comment]
You may want to enable `trust-remote-code`.

**Comment by hacbachvotu** [comment]
> You may want to enable `trust-remote-code`.

![z4879988718785_17f448df3586dc037c171268ea8d4d3d](https://github.com/VinAIResearch/PhoGPT/assets/124884827/bfbf5816-6fbf-4ffc-8319-735258594d41)
![z4879989253645_8f641a4783fd3a083f1eb79e9bc60c3a](https://github.com/VinAIResearch/PhoGPT/assets/124884827/417b3b3e-b112-4785-ba87-0ae34fd2b60c)
Thanks for you help! It's work with trust-remote-code Flag.

**Comment by datquocnguyen** [comment]
For the model to work properly, you might need to insert/use the PROMPT template `"### Câu hỏi:\n{instruction}\n\n### Trả lời:"`.

**Comment by hacbachvotu** [comment]
> For the model to work properly, you might need to insert/use the PROMPT template `"### Câu hỏi:\n{instruction}\n\n### Trả lời:"`.

![z4880987097593_1f879b805c32207997b9dcd094ee57d2](https://github.com/VinAIResearch/PhoGPT/assets/124884827/35550040-cd33-4a0e-9862-eb68894f5038)
Let me ask one more question: is it correct to put this prompt in oobooga?

**Comment by AlexBlack2202** [comment]
> ### Câu hỏi:\n{instruction}\n\n### Trả lời:"



> > For the model to work properly, you might need to insert/use the PROMPT template `"### Câu hỏi:\n{instruction}\n\n### Trả lời:"`.
> 
> ![z4880987097593_1f879b805c32207997b9dcd094ee57d2](https://private-user-images.githubusercontent.com/124884827/282845490-35550040-cd33-4a0e-9862-eb68894f5038.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MDA1MTYsIm5iZiI6MTcwMjgwMDIxNiwicGF0aCI6Ii8xMjQ4ODQ4MjcvMjgyODQ1NDkwLTM1NTUwMDQwLWNkMzMtNGEwZS05ODYyLWViNjg4OTRmNTAzOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwODAzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzc2M2NjMzAwMjQzYTA4MjcyMGYxMDBlMWIwNWI0ZWIzMDNkNjA1ODc1OWNjMTlmMjI5ODVjYjU3ODY2NGJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6IReYQBYrvoAegIrJSc6NkR5T_yOuK2fbX2_6jmTtAE) Let me ask one more question: is it correct to put this prompt in oobooga?

do you know how to correct this?, i have same question
