### ISSUE TITLE
Any online demo available?

### ISSUE THREAD

**Issue by anguyen8** [VinAIResearch/PhoGPT#8]
Congratulations! This is great work!!! Particularly, for the Vietnamese community around the world!

Do you have any plans for releasing an online demo of PhoGPT (perhaps a HuggingFace online demo)? :)

**Comment by datquocnguyen** [comment]
Thanks. I am quite confident in the safety level of our current instruction model, but there might still be cases where others attempt to jailbreak it. So, as of now, it's a No.
