### ISSUE TITLE
Could you explain what is the diference the non-instruct and instruct PhoGPT verrsion ? 

### ISSUE THREAD

**Issue by leviethung2103** [VinAIResearch/PhoGPT#9]
Hi Mr Dat,

First of all, thank you so much for this great project. 

I am reaching out to seek clarification regarding the distinctions between the non-instruct and instruct versions of PhoGPT.

I've come across discussions about these two versions and would greatly appreciate it if you could provide some insights into their key differences. Specifically, I am curious about how their functionalities vary and what specific use cases each version is optimized for.

Thank you very much for your time and assistance. I look forward to gaining a better understanding of the distinctions between the non-instruct and instruct versions of PhoGPT.

**Comment by datquocnguyen** [comment]
<img width="667" alt="Screen Shot 2023-11-30 at 11 31 34 pm" src="https://github.com/VinAIResearch/PhoGPT/assets/2412555/44ae4f61-009b-46cc-a293-eb7a8cbbeb78">
